In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
# Create paths to csv files
flights2021_path = 'Combined_Flights_2021.csv'
flights2022_path = 'Combined_Flights_2022.csv'

In [30]:
# Read the csv files = pd.read_csv(flights 2021 and 2022)
flights2021_data = pd.read_csv(flights2021_path)
flights2022_data = pd.read_csv(flights2022_path)

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [31]:
flights2021_data.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [33]:
flights2021_data.Airline.value_counts()

Southwest Airlines Co.                       1064640
SkyWest Airlines Inc.                         753343
Delta Air Lines Inc.                          747998
American Airlines Inc.                        736399
United Air Lines Inc.                         446837
Republic Airlines                             332926
Endeavor Air Inc.                             266867
Envoy Air                                     255751
Comair Inc.                                   222602
JetBlue Airways                               202702
Spirit Air Lines                              191361
Alaska Airlines Inc.                          188955
Mesa Airlines Inc.                            159789
Frontier Airlines Inc.                        137142
Allegiant Air                                 115881
Horizon Air                                   111628
Capital Cargo International                    99331
Air Wisconsin Airlines Corp                    80256
Commutair Aka Champlain Enterprises, Inc.      76666
Hawaiian Airlines Inc.                         60542
GoJet Airlines, LLC d/b/a United Express       60143
Empire Airlines Inc.                             112
Name: Airline, dtype: int64

In [34]:
#Filtering the data to just two airlines Hawaiian Airlines Inc and Horizon Air

key1 = flights2021_data.Airline == "Hawaiian Airlines Inc."
key2 = flights2021_data.Airline == "Horizon Air"

filter_airline21 = flights2021_data[key1 | key2]

#filter_dest_21 = flights2021_data[flights2021_data.Dest == ["MIA" , "PHX"]]

filter_airline21

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
50315,2021-03-01,Horizon Air,YKM,SEA,False,False,530,521.0,0.0,-9.0,...,526.0,554.0,4.0,613,-15.0,0.0,-1.0,0600-0659,1,0.0
50316,2021-03-01,Horizon Air,SEA,YKM,False,False,1240,1235.0,0.0,-5.0,...,1243.0,1307.0,4.0,1330,-19.0,0.0,-2.0,1300-1359,1,0.0
50317,2021-03-01,Horizon Air,YKM,SEA,False,False,1410,1406.0,0.0,-4.0,...,1410.0,1443.0,6.0,1453,-4.0,0.0,-1.0,1400-1459,1,0.0
50318,2021-03-01,Horizon Air,SEA,YKM,False,False,2255,2250.0,0.0,-5.0,...,2302.0,2332.0,5.0,2341,-4.0,0.0,-1.0,2300-2359,1,0.0
50319,2021-03-01,Horizon Air,AUS,SAN,False,False,1720,1717.0,0.0,-3.0,...,1730.0,1821.0,2.0,1825,-2.0,0.0,-1.0,1800-1859,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6257370,2021-06-30,Horizon Air,SEA,EUG,False,False,2122,2132.0,10.0,10.0,...,2148.0,2234.0,4.0,2229,9.0,0.0,0.0,2200-2259,1,0.0
6257371,2021-06-30,Horizon Air,SEA,BOI,False,False,1800,1756.0,0.0,-4.0,...,1813.0,2023.0,5.0,2030,-2.0,0.0,-1.0,2000-2059,2,0.0
6257372,2021-06-30,Horizon Air,MFR,SEA,False,False,2030,2026.0,0.0,-4.0,...,2035.0,2143.0,7.0,2155,-5.0,0.0,-1.0,2100-2159,2,0.0
6257373,2021-06-30,Horizon Air,SEA,MSO,False,False,1517,1526.0,9.0,9.0,...,1548.0,1800.0,4.0,1745,19.0,1.0,1.0,1700-1759,2,0.0
6257374,2021-06-30,Horizon Air,SEA,STS,False,False,1100,1106.0,6.0,6.0,...,1119.0,1249.0,20.0,1305,4.0,0.0,0.0,1300-1359,3,0.0

In [36]:
#Filtering the data to just two airlines Hawaiian Airlines Inc and Horizon Air

key1 = flights2022_data.Airline == "Hawaiian Airlines Inc."
key2 = flights2022_data.Airline == "Horizon Air"

filter_airline22 = flights2022_data[key1 | key2]

#filter_dest_22 = flights2022_data[flights2021_data.Dest == ["MIA" , "PHX"]]

filter_airline22

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
379252,2022-04-01,Hawaiian Airlines Inc.,LAX,HNL,False,False,700,701.0,1.0,1.0,...,718.0,942.0,11.0,1005,-12.0,0.0,-1.0,1000-1059,11,0
379253,2022-04-02,Hawaiian Airlines Inc.,LAX,HNL,False,False,700,653.0,0.0,-7.0,...,708.0,959.0,14.0,1005,8.0,0.0,0.0,1000-1059,11,0
379254,2022-04-03,Hawaiian Airlines Inc.,LAX,HNL,False,False,700,706.0,6.0,6.0,...,717.0,938.0,19.0,1005,-8.0,0.0,-1.0,1000-1059,11,0
379255,2022-04-04,Hawaiian Airlines Inc.,LAX,HNL,False,False,700,656.0,0.0,-4.0,...,710.0,932.0,9.0,1005,-24.0,0.0,-2.0,1000-1059,11,0
379256,2022-04-05,Hawaiian Airlines Inc.,LAX,HNL,False,False,700,657.0,0.0,-3.0,...,710.0,938.0,8.0,1005,-19.0,0.0,-2.0,1000-1059,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3866243,2022-03-31,Horizon Air,PDX,SLC,False,False,700,654.0,0.0,-6.0,...,703.0,932.0,26.0,949,9.0,0.0,0.0,0900-0959,3,0
3866244,2022-03-31,Horizon Air,SLC,PDX,False,False,1030,1031.0,1.0,1.0,...,1042.0,1121.0,3.0,1133,-9.0,0.0,-1.0,1100-1159,3,0
3866245,2022-03-31,Horizon Air,RNO,PDX,False,False,2025,2024.0,0.0,-1.0,...,2035.0,2147.0,3.0,2154,-4.0,0.0,-1.0,2100-2159,2,0
3866246,2022-03-31,Horizon Air,PDX,RNO,False,False,1810,1804.0,0.0,-6.0,...,1812.0,1920.0,3.0,1936,-13.0,0.0,-1.0,1900-1959,2,0
3866247,2022-03-31,Horizon Air,GEG,SFO,False,False,1200,1208.0,8.0,8.0,...,1220.0,1402.0,3.0,1408,-3.0,0.0,-1.0,1400-1459,3,0

In [21]:
df = pd.merge(filter_airline21, filter_airline22, how="left", on= "Airline")

MemoryError: Unable to allocate 187. TiB for an array with shape (25741817112978,) and data type int64

In [10]:
# Combine the data into a single dataset
df = pd.merge(flights2021_data, flights2022_data, how="left", on="FlightDate")

# Display the data table for preview
df

,FlightDate,Airline_x,Origin_x,Dest_x,Cancelled_x,Diverted_x,CRSDepTime_x,DepTime_x,DepDelayMinutes_x,DepDelay_x,...,WheelsOff_y,WheelsOn_y,TaxiIn_y,CRSArrTime_y,ArrDelay_y,ArrDel15_y,ArrivalDelayGroups_y,ArrTimeBlk_y,DistanceGroup_y,DivAirportLandings_y
0,2021-03-03,SkyWest Airlines Inc.,SGU,PHX,False,False,724,714.0,0.0,-10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-03,SkyWest Airlines Inc.,PHX,SGU,False,False,922,917.0,0.0,-5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-03,SkyWest Airlines Inc.,MHT,ORD,False,False,1330,1321.0,0.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-03,SkyWest Airlines Inc.,DFW,TRI,False,False,1645,1636.0,0.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-03,SkyWest Airlines Inc.,PHX,BFL,False,False,1844,1838.0,0.0,-6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6311866,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,1255,1301.0,6.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311867,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,730,727.0,0.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311868,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,800,757.0,0.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311869,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,1300,1252.0,0.0,-8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311870,2021-06-01,Southwest Airlines Co.,BNA,MKE,False,False,1925,1948.0,23.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

#check if there are any duplicates and drop them 

# making a bool series
flights_dup = df.duplicated(keep = False)
 
# bool series
flights_dup
 
# passing NOT of bool series to see unique values only
raw_data_df1 = df[~flights_dup]
 
# displaying data
raw_data_df1.info()
raw_data_df1

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6311871 entries, 0 to 6311870
Columns: 121 entries, FlightDate to DivAirportLandings_y
dtypes: bool(2), float64(60), int64(22), object(37)
memory usage: 5.7+ GB

,FlightDate,Airline_x,Origin_x,Dest_x,Cancelled_x,Diverted_x,CRSDepTime_x,DepTime_x,DepDelayMinutes_x,DepDelay_x,...,WheelsOff_y,WheelsOn_y,TaxiIn_y,CRSArrTime_y,ArrDelay_y,ArrDel15_y,ArrivalDelayGroups_y,ArrTimeBlk_y,DistanceGroup_y,DivAirportLandings_y
0,2021-03-03,SkyWest Airlines Inc.,SGU,PHX,False,False,724,714.0,0.0,-10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-03,SkyWest Airlines Inc.,PHX,SGU,False,False,922,917.0,0.0,-5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-03,SkyWest Airlines Inc.,MHT,ORD,False,False,1330,1321.0,0.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-03,SkyWest Airlines Inc.,DFW,TRI,False,False,1645,1636.0,0.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-03,SkyWest Airlines Inc.,PHX,BFL,False,False,1844,1838.0,0.0,-6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6311866,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,1255,1301.0,6.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311867,2021-06-01,Southwest Airlines Co.,BNA,MDW,False,False,730,727.0,0.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311868,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,800,757.0,0.0,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311869,2021-06-01,Southwest Airlines Co.,BNA,MIA,False,False,1300,1252.0,0.0,-8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6311870,2021-06-01,Southwest Airlines Co.,BNA,MKE,False,False,1925,1948.0,23.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#clean_data_df = pd.DataFrame([raw_data_df1])
#clean_data_df

#clean_data_df = raw_data_df1.drop(columns=['WheelsOff_y', 'WheelsOn_y', "TaxiIn_y", "CRSArrTime_y", 
               #"ArrDelay_y", "ArrDel15_y" , "ArrivalDelayGroups_y", "ArrTimeBlk_y"])

#clean_data_df=clean_data_df.dropna()
#clean_data_df.reset_index()
#clean_data_df.head()